### ISSUE TITLE
Missing Volume in WebSite2

### ISSUE THREAD

**Issue by peterbladen** [kassambara/nginx-multiple-https-websites-on-one-server#1]
Nice scripts and i followed them as shown, but there is a line missing from https://github.com/kassambara/nginx-multiple-https-websites-on-one-server/blob/master/your-website-two.com/docker-compose.yml it needs the following 

 volumes:
      - "./:/usr/share/nginx/html"

Which is in website-one docker-compose - the default nginx page is displayed without it

**Comment by kassambara** [comment]
Thank you for pointing this out, fixed now!
